-- SELECT - 역순 정렬하기 (Oracle)

-- 내 풀이
SELECT NAME, DATETIME
FROM (SELECT *
      FROM ANIMAL_INS
      ORDER BY ANIMAL_ID DESC);

-- 다른 풀이
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;