-- SELECT - 조건에 부합하는 중고거래 댓글 조회하기 (Oracle)

-- 내 풀이
SELECT BOARD.TITLE AS TITLE,
       BOARD.BOARD_ID AS BOARD_ID,
       REPLY.REPLY_ID AS REPLY_ID,
       REPLY.WRITER_ID AS WRITER_ID,
       REPLY.CONTENTS AS CONTENTS,
       TO_CHAR(REPLY.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD BOARD, USED_GOODS_REPLY REPLY
WHERE BOARD.BOARD_ID = REPLY.BOARD_ID
      AND TO_CHAR(BOARD.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC;